### ISSUE TITLE
Chinese/English l18n and UX problems

### ISSUE THREAD

**Issue by casprussian** [codex-studio/nav#10]
On Mozilla/5.0 (X11; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0:

1. User navigates to nav.codex.studio
2. ISSUE: Splash screen seems to randomly choose between Chinese and English
2a. ISSUE: If splash screen does direct to English, then it takes a glaring delay as it starts with Chinese for a split second and then changes to English
3. Main page loads
4. IMPROVEMENT: Why does the "Welcome back, $USERNAME" box appear in such a strange place. It throws off the "balance" of the page. It should come up from the bottom and stay say, in between the search form and the logo for a bit then fly up.
5. STRONG WARNING: The notepad function is nice, but always remember that the client side is NEVER secure.
6. IMPROVEMENT: The date function in the top right is too close to the edge of the page.
7. WARNING: @mj66 Remember when you showed me that extremely cluttered Chinese search engine? I fear that will happen to the page. For a Good UX, each category should be collapsed at the beginning.
8. IMPROVEMENT: If you added the idea of the notepad, then you should allow the user to add their own links to each category.

@mj66 Have you tried pushing upstream changes for PHP on Github yet?
@mj66 Sorry I couldn't get on GHub for the past week, I was at camp.

**Comment by mj66** [comment]
Welcome back. Here's my response.
1. /
2. If you would notice, you will find that the language was not "randomly" jumping. It was determined by the LAST USED LANGUAGE. For instance, for the first time we navigated you to the English site and you manually clicked back to the Chinese site. Then, we will write a cookie to notify our server that this man would prefer Chinese than the English site which we automatically configured for him. So next time he opens up the webpage, he would be redirected to the Chinese page instead of the English page. That way we are following the user's preference.
3. /
4. We are only following the Google's Material Design documentation which states that the notification SHOULD appear there. No other reasons. FYI, in mobile, the notification bar will appear at the bottom of the page and can be dismissed by swiping.
5. This is just a notepad. The tool itself is not designed to be safe - we will store is as COOKIES on the browser, and as shown on the page, "ONLY LASTS FOR 2 DAYS" for security reasons. Basically, we store a file that's not encrypted to the user's browser, so that the user can actually notify himself something when he opens up the browser (of course if he set us as homepage first).
6. Well not really... What is your ideal distance?
7. We don't want users to make one more click in order to navigate to their target website. We want it to be fast. We will certainly do more on the classifying side on 3.x.
8. Nice idea. 2.x development stops at 7.20. That's what we have promised our users in China (of course it is just the "version #" that actually matters). On 3.x, we will focus on cookies, user customization, and relationships to our other projects. More details on QQ.

- GitHub only supports static web pages. PHP is an active and interactive one. So no, and I will never waste my time on PHP. Javascript is more worth my time.
- I heard that you are going to move sometime this summer? 

Anyway, see you on QQ. I've sent you a couple of things there. I guess we could meet sometime to discuss some focusing points of NAV 3.0.

**Comment by casprussian** [comment]
@mj66 
QQ international isn't working on my new iOS?

**Comment by mj66** [comment]
Should... What iOS are you using?
