### ISSUE TITLE
Recommendations on CodEX Nav

### ISSUE THREAD

**Issue by liangyiliang** [codex-studio/nav#8]
Hi All
I have some suggestions on the design of CodEX Nav. 
Firstly, just below the time, why is there a bar that says "navigation"? I know that the "changelog" was next to it, but I think it is better to remove that bar because the changelog is moved. 

Secondly, I recommend to make a small pop-up window when the "changelog" is clicked. it is awkward to just jump to another page. 

These are my recommendations. 

Thanks. 
Leo Liang

**Comment by mj66** [comment]
1. Changelog is removed because we are going to add something interesting (阴吹思厅) to the page. But before the new thing is live, yes we can temporarily remove the tabs.
2. That is exactly what @casprussian and I were thinking about. We are still working on it to make the mobile UX better, and it won't be long.

I will close this issue as soon as the tab is temporarily removed. Thanks.

**Comment by mj66** [comment]
Tabs is now temporarily removed. Thanks for the suggestion.
